on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Cache node_modules using Yarn
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      # Install dependencies using Yarn
      - run: yarn install --frozen-lockfile

      # Build all workspaces (replace with specific packages if needed)
      - run: yarn workspaces run build

      # Run tests across all workspaces (replace with specific packages if needed)
      - run: yarn workspaces run test

      # Install Cypress binaries (if used)
      - run: npx cypress install

      # Run Cypress tests (replace with specific package if needed)
      - run: yarn workspace <package-name> cypress run
